# -*- coding: utf-8 -*-
"""sistem panen

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Y9KwAvrlBEpiW89iA3ZuhHsu76t7XIvh
"""

# Program Penghitung Total Hasil Panen
def hitung_total_panen(jumlah_kg, harga_per_kg):
    subtotal = jumlah_kg * harga_per_kg
    return subtotal

# Input data dari pengguna
print("=== SISTEM PENCATATAN HASIL PANEN ===")
nama_komoditas = input("Masukkan nama komoditas (misal: Padi/Jagung) : ")
jumlah_kg = float(input("Masukkan jumlah hasil panen (kg)           : "))
harga_per_kg = float(input("Masukkan harga per kg (Rp)                 : "))

# Perhitungan
total_pendapatan = hitung_total_panen(jumlah_kg, harga_per_kg)

# Menampilkan hasil
print("\n=== RINGKASAN PANEN ===")
print(f"Komoditas       : {nama_komoditas}")
print(f"Total Panen     : {jumlah_kg:.2f} kg")
print(f"Harga / kg      : Rp {harga_per_kg:,.0f}")
print(f"Total Hasil     : Rp {total_pendapatan:,.0f}")
